Update Project
datenlord/blake2b_compress pull request #4
Opened 2021-10-19 12:42 UTC by wengwz

Changes:
1) convert Chinese readme to English version;
2) update testbench with the function of checking whether the output is consistent with reference model
3) update code style and pass linter check
4) update run.sh

2021-10-19 13:08 UTC, pwang7 requested changes

2021-10-19 13:08 UTC, pwang7 commented on src/blake2b_compress.v
> +  wire [   `ROUND_INDEX_BUS]  round_connection [25];
align the right bracket with the previous line

2021-10-19 13:08 UTC, pwang7 commented on run.sh
> +set -o errexit # TODO: enable this check
remove TODO comment

2021-10-19 13:08 UTC, pwang7 commented on run.sh
> +#VERIFICATION_DIR = verificatioin
remove commented line

2021-10-19 13:08 UTC, pwang7 commented on src/blake2b_sigma.v
> +    case (sigma_column_i)
too much duplicated code, is it possible to use generate?

2021-10-19 13:08 UTC, pwang7 commented on src/testbench.v
> +  localparam reg Period = 10;
use call capital word for parameter and local parameter

2021-10-19 13:08 UTC, pwang7 commented on verification/blake2b_compress.c
> +
remove empty line after return

2021-10-19 14:16 UTC, wengwz commented on src/blake2b_sigma.v
> +    case (sigma_column_i)
This module implements a lookup table. And every always_comb in the module implements one row in the lookup table. Beacuse values in different rows are irregular, so it's hard to use generate to implement different lines.

2021-10-19 15:33 UTC, pwang7 requested changes

2021-10-19 15:33 UTC, pwang7 commented on run.sh
> -git diff --exit-code # Fail if any format change
you have to rebase onto the latest head of the upstream/master branch

2021-10-21 07:10 UTC, bit-rage approved these changes
okay

2021-10-21 07:13 UTC, bit-rage approved these changes

2021-10-23 14:07 UTC, pwang7 approved these changes

2021-10-23 14:08 UTC, merged